[workspace]
authors = ["Edwin Hu <eddyhu@gmail.com>"]
channels = ["conda-forge"]
name = "xeus-sas"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
xeus = ">=5.2.4,<6"
xeus-zmq = ">=3.1.1,<4"
xtl = ">=0.8.1,<0.9"
nlohmann_json = ">=3.12.0,<4"
cmake = ">=4.1.2,<5"
cxx-compiler = ">=1.11.0,<2"
gtest = ">=1.17.0,<2"
